name: Bug Report
description: File a reproducible bug or regression.
labels: ['bug']
body:
  - type: textarea
    id: graph
    attributes: 
      label: Resources 
      value: | 
        Related Issues:
        Related PRs:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem (drag and drop the image).
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: false
      options: 
        - 🌋 Urgent
        - 🏔 High
        - 🏕 Medium
        - 🏝 Low
  - type: dropdown
    id: size
    attributes:
      label: Size
      multiple: false
      options: 
        - 🐋 X-Large
        - 🦑 Large
        - 🐂 Medium
        - 🐇 Small
        - 🦔 Tiny
  - type: dropdown
    id: department
    attributes:
      label: Department
      multiple: false
      options:
        - IT 
        - HR
        - Finance
        - Operations
        - Warehouse
        - Management
        - Customer