blank_issues_enabled: false
contact_links:
  - name: Help and Support
    url: https://1clicklogistics.atlassian.net/wiki/spaces/KB/overview?homepageId=98526
    about: Please refer to our Confluence page for additional assistance.