name: Data Update
description: Update data values within the repository.
labels: ['update']
title: "Data Update - "
body:
  - type: textarea
    id: graph
    attributes: 
      label: Resources 
      value: | 
        Related Issues:
        Related PRs:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: dataLocation
    attributes:
      label: Data Location
      description: Indicate where the data is located.
    validations:
      required: true