name: Data Update
description: Update data values within the repository.
labels: ['Update']
title: "Data Update - "
body:
  - type: textarea
    id: graph
    attributes: 
      label: Resources 
      value: | 
        Related Issues:
        Related PRs:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: An analysis of the data being updated and the reasons for updating it.
    validations:
      required: true
  - type: textarea
    id: dataValidation
    attributes:
      label: Data Validation
      description: If necessary, describe how the data was validated.
    validations:
      required: false