name: Feature Request
description: Suggest an idea for the project.
labels: ['feature']
body:
  - type: textarea
    id: graph
    attributes: 
      label: Resources
      value: |
        Modify the fields below to represent the relevant items or resources affected by your PR:
        **Related Issues**:
        **Related PRs**: 
        **Pages**: 
        **Database Tables**:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
    validations:
      required: false
      - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: false
      options: 
        - 🌋 Urgent
        - 🏔 High
        - 🏕 Medium
        - 🏝 Low
  - type: dropdown
    id: size
    attributes:
      label: Size
      multiple: false
      options: 
        - 🐋 X-Large
        - 🦑 Large
        - 🐂 Medium
        - 🐇 Small
        - 🦔 Tiny
  - type: dropdown
    id: department
    attributes:
      label: Department
      multiple: false
      options:
        - IT 
        - HR
        - Finance
        - Operations
        - Warehouse
        - Management
        - Customer