name: Feature Request
description: Suggest an idea for the project.
labels: ['Feature']
body:
  - type: textarea
    id: graph
    attributes: 
      label: Resources
      value: |
        **Related Issues**:
        **Related PRs**: 
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Feature Due Date:"
  - type: dropdown
    id: month
    attributes:
      label: "Month"
      description: "Select the month"
      options:
        - January
        - February
        - March
        - April
        - May
        - June
        - July
        - August
        - September
        - October
        - November
        - December
    validations:
      required: true
  - type: dropdown
    id: day
    attributes:
      label: "Day"
      description: "Select the day"
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
    validations:
      required: true
  - type: dropdown
    id: year
    attributes:
      label: "Year"
      description: "Select the year"
      options:
        - "2023"
        - "2024"
        - "2025"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
    validations:
      required: false