name: Add Assignment Date to Project

on:
  issues:
    types: [assigned]

jobs: 
  auto_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
        with: 
          sparse-checkout: .github
      - name: Get Project Data.
        env:
          ORGANIZATION: chelgeson1click
          PROJECT_NUMBER: 2
          GH_TOKEN: ${{ secrets.PROJECT_PAT_TOKEN }}
        run: gh api graphql -f query="$(cat ./.github/schema/getProjectInfo.graphql)" > project_data.json
      - name: List files to check if project_data.json was generated.
        run: cat project_data.json

