name: Auto-Label Issue From Title

on:
  issues:
    types: [opened]

jobs: 
  assign_due_date: 
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps: 
      - name: Extract Issue Due Date
        run: |
          ISSUE_BODY="${{github.event.issue.body}}"
          MONTH=$(echo "$ISSUE_BODY" | grep -oP -e '(?<=Month\n\s\s\n\s\s)(\w*)(?=\n\s\s\n\s\s\#)' || date +%B)
          DAY=$(echo "$ISSUE_BODY" | grep -oP -e '(?<=Day\n\s\s\n\s\s)(\w*)(?=\n\s\s\n\s\s\#)' || date +%d)
          YEAR=$(echo "$ISSUE_BODY" | grep -oP -e '(?<=Year\n\s\s\n\s\s)(\w*)(?=\n\s\s\n\s\s\#)' || date +%Y)

          echo $MONTH

          case "$MONTH" in
            "January") MONTH_NUM="01" ;;
            "February") MONTH_NUM="02" ;;
            "March") MONTH_NUM="03" ;;
            "April") MONTH_NUM="04" ;;
            "May") MONTH_NUM="05" ;;
            "June") MONTH_NUM="06" ;;
            "July") MONTH_NUM="07" ;;
            "August") MONTH_NUM="08" ;;
            "September") MONTH_NUM="09" ;;
            "October") MONTH_NUM="10" ;;
            "November") MONTH_NUM="11" ;;
            "December") MONTH_NUM="12" ;;
            *) echo "Invalid month"; exit 1 ;;
          esac

          echo ${MONTH}
          echo ${DAY}
          echo ${YEAR}
  auto_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Assign labels from titles.
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          LABELS=""
          case "$ISSUE_TITLE" in 
            *Components*)
              echo "Adding React and Javascript labels to issue."
              LABELS="React,Javascript"
              ;;
            *DevOps* | *"Dev Ops"*)
              echo "Adding Dev Ops label to issue."
              LABELS="Dev Ops"
              ;;
            *Documentation*)
              echo "Adding Documentation label to issue." 
              LABELS="Documentation"
              ;;
            esac

            echo "LABELS=$LABELS" >> $GITHUB_ENV
      - name: Apply label to issue.
        if: env.LABELS != ''
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ${{ env.LABELS }}

         
