name: Auto-Label Issue From Title

on:
  issues:
    types: [opened]

jobs: 
  auto_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Assign labels from titles.
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          LABELS=""
          case "$ISSUE_TITLE" in 
            *Components*)
              echo "Adding React and Javascript labels to issue"
              LABELS="React,Javascript"
              ;;
            *DevOps* | *"Dev Ops"*)
              echo "Adding Dev Ops label to issue"
              LABELS="Dev Ops"
              ;;
            *Documentation*)
              echo "Adding Documentation label to issue" 
              LABELS="Documentation"
              ;;
            esac

            echo "LABELS=$LABELS" >> $GITHUB_ENV
      - name: Apply label to issue.
        if: env.LABELS != ''
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ${{ env.LABELS }}
         
