name: Add Assignment Date to Project

on:
  issues:
    types: [assigned]

jobs: 
  auto_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
        with: 
          sparse-checkout: .github
      - name: Setup Global Variables
        env:
          SCRIPT_PATH: './.github/scripts'
        run: |
          echo 'SCRIPT_PATH='${SCRIPT_PATH} >> $GITHUB_ENV
      - name: Get Project Data.
        env:
          ORGANIZATION: chelgeson1click
          PROJECT_NUMBER: 2
          GH_TOKEN: ${{ secrets.PROJECT_PAT_TOKEN }}
          SCRIPT_PATH: './.github/scripts'
        run: |

          source ${SCRIPT_PATH}/projectWorkflow.sh

          runGraphQLQuery 'getProjectInfo' 'project_data.json'
          cat project_data.json
          
          echo 'PROJECT_ID='$(jq '.data.user.projectV2.id' project_data.json) >> $GITHUB_ENV
          getProjectVariableID 'STATUS_FIELD_ID' 'Status'
          getProjectVariableID 'ASSIGNMENT_DATE_ID' 'Assigned Date'
          echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          
      - name: Validate project variables.
        run: |
          echo $PROJECT_ID
          echo $STATUS_FIELD_ID
          echo $ASSIGNMENT_DATE_ID
          echo $DATE
      - name: Add issue to project.
        env:
          GH_TOKEN: ${{ secrets.PROJECT_PAT_TOKEN }}
          ITEM_ID: ${{ github.event.issue.node_id }}
        run: |
          source ${SCRIPT_PATH}/projectWorkflow.sh
          
          runGraphQLMutation 'addIssueToProject' test_data.json "$PROJECT_ID" "$ITEM_ID"
          cat test_data.json
          getProjectItemID test_data.json 'PROJECT_ITEM_ID'
          echo $PROJECT_ITEM_ID



          

