name: Add Assignment Date to Project

on:
  issues:
    types: [assigned]

jobs: 
  auto_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
        with: 
          sparse-checkout: .github
      - name: Get Project Data.
        env:
          ORGANIZATION: chelgeson1click
          PROJECT_NUMBER: 2
          GH_TOKEN: ${{ secrets.PROJECT_PAT_TOKEN }}
        run: |
          gh api graphql -f query="$(cat ./.github/schema/getProjectInfo.graphql)" > project_data.json
          cat project_data.json

          get_project_var_id() {
            local envVarName=$1
            local fieldVarName=$2

            local field_id=$(jq ".data.user.projectV2.fields.nodes[] | select(.name==\"${fieldVarName}\") | .id" project_data.json)
            echo "${envVarName}=${field_id}" >> $GITHUB_ENV
          }

          echo 'PROJECT_ID='$(jq '.data.user.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'DATE_FIELD_ID='$(jq '.data.user.projectV2.fields.nodes[] | select(.name== "Date posted") | .id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.user.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'TODO_OPTION_ID='$(jq '.data.user.projectV2.fields.nodes[] | select(.name== "Todo") | .options[] | select(.name=="Todo") |.id' project_data.json) >> $GITHUB_ENV
          get_project_var_id 'ASSIGNMENT_DATE_ID' 'Assigned Date'
      - name: Validate project variables.
        run: |
          echo $PROJECT_ID
          echo $DATE_FIELD_ID
          echo $STATUS_FIELD_ID
          echo $TODO_OPTION_ID
          echo $ASSIGNMENT_DATE_ID

