name: Modify Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs: 
  call_on_item_open:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Deploy Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Node Clean Install
        run: npm ci

      - name: Access PR Body as JSON
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          issue-body: ${{ github.event.pull_request.body }}

      - name: Log PR Body
        run: cat ${HOME}/issue-parser-result.json
      
      - name: Extract Issue Project ID and Project Fields
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_PAT_TOKEN }}
          script: |
            const path = '${{ github.workspace }}/.github/scripts/;
            const { getIssueItemID, getProjectFieldIDs } = await import(`${path}/pr.js`)
            const itemIDVars = {
              issueNumber: 37,
            }

            const prID = ${{github.event.pull_request.node_id}}
            console.log(prID)

            const projectItemID = await getIssueItemID({github, itemIDVars});
            const { priorityFieldID, sizeFieldID, departmentFieldID } = await getProjectFieldIDs({github});






