name: Modify Pull Request

on:
  pull_request:
    types: [opened]

jobs: 
  auto_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
        with: 
          sparse-checkout: .github

      - name: Access PR Body as JSON
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          issue-body: ${{ github.event.pull_request.body }}

      - name: Log PR Body
        run: cat ${HOME}/issue-parser-result.json

