name: Modify Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs: 
  call_on_item_open:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Deploy Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Node Clean Install
        run: npm ci

      - name: Access PR Body as JSON
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          issue-body: ${{ github.event.pull_request.body }}

      - name: Log PR Body
        run: cat ${HOME}/issue-parser-result.json
      
      - name: Extract Issue Project ID
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_PAT_TOKEN }}
          script: |
            const { getIssueInfo } = await import('${{ github.workspace }}/.github/scripts/pr.js')
            const variables = {
              issueNumber: 20,
            }

            await getIssueInfo({github, variables})

      - name: Extract Issue Fields
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_PAT_TOKEN }}
          script: |
            const { getProjectInfo } = await import('${{ github.workspace }}/.github/scripts/pr.js')

            await getProjectInfo({github})


